# Experiment configuration for rover domain with enhanced metrics
# Complex domain with navigation and sampling tasks

experiment:
  name: "rover_detailed"
  algorithm: "olam"
  seed: 42

domain_problem:
  domain: "benchmarks/rover/domain.pddl"
  problem: "benchmarks/rover/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  olam:
    max_iterations: 400
    eval_frequency: 20

# Metrics collection - record EVERY action
metrics:
  interval: 1  # Record every single action
  window_size: 50  # Default window

# Enhanced logging configuration
logging:
  level: "DEBUG"
  console_level: "INFO"
  file_level: "DEBUG"
  log_state_transitions: true
  log_action_selections: true
  log_learning_updates: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s"

# Stopping criteria
stopping_criteria:
  max_iterations: 300
  max_runtime_seconds: 900  # 15 minutes for complex domain
  convergence_check_interval: 30

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  save_intermediate_checkpoints: true
  checkpoint_interval: 75