# Experiment configuration for depots domain with enhanced metrics
# More complex domain with logistics operations

experiment:
  name: "depots_detailed"
  algorithm: "olam"
  seed: 42

domain_problem:
  domain: "benchmarks/olam-compatible/depots/domain.pddl"
  problem: "benchmarks/olam-compatible/depots/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  olam:
    max_iterations: 300
    eval_frequency: 15
    bypass_java: true  # No Java available - use Python fallback

# Metrics collection - record EVERY action
metrics:
  interval: 1  # Record every single action
  window_size: 50  # Default window

# Enhanced logging configuration
logging:
  level: "DEBUG"
  console_level: "INFO"
  file_level: "DEBUG"
  log_state_transitions: true
  log_action_selections: true
  log_learning_updates: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Stopping criteria
stopping_criteria:
  max_iterations: 250
  max_runtime_seconds: 600
  convergence_check_interval: 25

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  save_intermediate_checkpoints: true
  checkpoint_interval: 50