# Experiment configuration for Logistics domain
experiment:
  name: "logistics_learning"
  domain: "benchmarks/logistics/domain.pddl"
  problem: "benchmarks/logistics/p01.pddl"
  algorithms:
    - olam
  metrics:
    - mistake_rate
    - cumulative_mistakes
    - per_action_success_rate
    - runtime
  stopping_criteria:
    max_iterations: 1000
    convergence_threshold: 0.95
    check_convergence_every: 20
    timeout: 600  # 10 minutes
  output:
    directory: "results/logistics"
    formats: ["csv", "json"]
  random_seed: 42

# Algorithm-specific parameters
olam:
  exploration_rate: 0.1
  max_learning_iterations: 100