# Sample experiment configuration for online action model learning
# This configuration runs the OLAM baseline on blocksworld domain

experiment:
  name: "olam_baseline_blocksworld"
  algorithm: "olam"  # Options: olam, information_gain, model_learner
  seed: 42  # Random seed for reproducibility

domain_problem:
  domain: "benchmarks/olam-compatible/blocksworld/domain.pddl"
  problem: "benchmarks/olam-compatible/blocksworld/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  olam:
    max_iterations: 1000
    eval_frequency: 10  # How often to evaluate the learned model

  # Future: Information gain parameters
  information_gain:
    exploration_weight: 0.5
    uncertainty_threshold: 0.1

  # Future: ModelLearner parameters
  model_learner:
    optimism_bias: 0.8
    batch_size: 50

# Metrics collection configuration
metrics:
  interval: 10  # Collect metrics every N steps
  window_size: 50  # Sliding window for mistake rate calculation

# Stopping criteria for the experiment
stopping_criteria:
  max_iterations: 1000  # Maximum number of action executions
  max_runtime_seconds: 3600  # Maximum runtime in seconds (1 hour)
  convergence_check_interval: 100  # Check convergence every N iterations

# Output configuration
output:
  directory: "results/"  # Directory to save results
  formats: ["csv", "json"]  # Export formats for metrics
  save_learned_model: true  # Save the final learned model
  save_plots: false  # Generate and save metric plots (requires matplotlib)