# Information Gain 500-Iteration Extended Validation - Depots Domain
# Phase 2.5: Gather evidence of sustained learning with conservative convergence parameters

experiment:
  name: "information_gain_depots_500iter_extended_validation"
  algorithm: "information_gain"
  seed: 42

domain_problem:
  domain: "benchmarks/olam-compatible/depots/domain.pddl"
  problem: "benchmarks/olam-compatible/depots/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  information_gain:
    selection_strategy: "greedy"  # Always select max information gain
    max_iterations: 100

    # Conservative convergence parameters (prevent premature convergence)
    # These are more restrictive than the defaults to ensure full validation runs
    model_stability_window: 50      # No model changes for 50 iterations
    info_gain_epsilon: 0.001         # Very low information gain threshold
    success_rate_threshold: 0.98     # 98% success rate required
    success_rate_window: 50          # Calculate over last 50 actions

    # Note: Convergence requires ALL 3 criteria to be met simultaneously

# Metrics collection - record every action
metrics:
  interval: 1  # Record every single action for complete trace
  window_size: 50

# Stopping criteria - conservative settings
stopping_criteria:
  max_iterations: 100
  max_runtime_seconds: 1200  # 20 minutes maximum
  convergence_check_interval: 50  # Check every 50 iterations

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  track_learning_evidence: true  # Enable parameter-bound learning evidence tracking
