# Information Gain Algorithm - Rover Domain
# Uses Boltzmann (softmax) selection strategy
# Note: Rover has negative preconditions (OLAM-incompatible)

experiment:
  name: "information_gain_rover_boltzmann"
  algorithm: "information_gain"
  seed: 42
  environment_type: "pddl"

domain_problem:
  domain: "benchmarks/olam-incompatible/rover/domain.pddl"
  problem: "benchmarks/olam-incompatible/rover/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  information_gain:
    selection_strategy: "boltzmann"  # Probabilistic selection via softmax
    temperature: 1.0  # Temperature parameter for softmax (higher = more exploration)
    max_iterations: 300

# Metrics collection
metrics:
  interval: 1  # Record every action
  window_size: 50

# Stopping criteria
stopping_criteria:
  max_iterations: 300
  max_runtime_seconds: 900  # Rover domain is more complex
  convergence_check_interval: 30

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
