# Information Gain Algorithm - Gripper Domain
# Uses epsilon-greedy selection strategy (exploration with probability epsilon)

experiment:
  name: "information_gain_gripper_epsilon"
  algorithm: "information_gain"
  seed: 42
  environment_type: "pddl"

domain_problem:
  domain: "benchmarks/olam-compatible/gripper/domain.pddl"
  problem: "benchmarks/olam-compatible/gripper/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  information_gain:
    selection_strategy: "epsilon_greedy"  # Explore with probability epsilon
    epsilon: 0.1  # 10% random exploration
    max_iterations: 200

# Metrics collection
metrics:
  interval: 1  # Record every action
  window_size: 50

# Stopping criteria
stopping_criteria:
  max_iterations: 200
  max_runtime_seconds: 600
  convergence_check_interval: 20

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
