# Information Gain Algorithm - Logistics Domain
# Validation test with greedy selection

experiment:
  name: "information_gain_logistics_validation"
  algorithm: "information_gain"
  seed: 42

domain_problem:
  domain: "benchmarks/olam-compatible/logistics/domain.pddl"
  problem: "benchmarks/olam-compatible/logistics/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  information_gain:
    selection_strategy: "greedy"
    max_iterations: 100
    model_stability_window: 50
    info_gain_epsilon: 0.001
    success_rate_threshold: 0.98
    success_rate_window: 50

# Metrics collection
metrics:
  interval: 1  # Record every action
  window_size: 50

# Stopping criteria
stopping_criteria:
  max_iterations: 100
  max_runtime_seconds: 600
  convergence_check_interval: 50

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  track_learning_evidence: true
