# OLAM Algorithm - Depots Domain (300 iterations)
# Main experiment configuration for paper

experiment:
  name: "olam_depots_300"
  algorithm: "olam"
  seed: 42

domain_problem:
  domain: "benchmarks/olam-compatible/depots/domain.pddl"
  problem: "benchmarks/olam-compatible/depots/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  olam:
    max_iterations: 300
    eval_frequency: 10
    planner_time_limit: 240
    max_precs_length: 8
    neg_eff_assumption: false
    output_console: false
    random_seed: 42

# Metrics collection
metrics:
  interval: 1
  window_size: 50

# Stopping criteria
stopping_criteria:
  max_iterations: 300
  max_runtime_seconds: 1800  # 30 minutes max
  convergence_check_interval: 100

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  track_learning_evidence: true
