# OLAM 500-Iteration Extended Validation - Depots Domain
# Phase 2.5: Gather evidence of sustained learning over 500 iterations

experiment:
  name: "olam_depots_500iter_extended_validation"
  algorithm: "olam"
  seed: 42

domain_problem:
  domain: "benchmarks/olam-compatible/depots/domain.pddl"
  problem: "benchmarks/olam-compatible/depots/p01.pddl"

# Algorithm-specific parameters
algorithm_params:
  olam:
    max_iterations: 500
    eval_frequency: 10
    planner_time_limit: 240  # 4 minutes per planning call (conservative)
    max_precs_length: 8
    neg_eff_assumption: false
    output_console: false
    random_seed: 42

# Metrics collection - record every action
metrics:
  interval: 1  # Record every single action for complete trace
  window_size: 50

# Stopping criteria - conservative settings
stopping_criteria:
  max_iterations: 500
  max_runtime_seconds: 7200  # 2 hours maximum
  convergence_check_interval: 100  # Conservative - check every 100 iterations

# Output configuration
output:
  directory: "results/"
  formats: ["csv", "json"]
  save_learned_model: true
  track_learning_evidence: true  # Enable parameter-bound learning evidence tracking
